name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: sample-integration

      - name: Build Next.js app
        run: npm run build
        working-directory: sample-integration

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "sample-integration/*"
          target: "/home/bitnami/app"

      - name: SSH and restart app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/bitnami/app
            npm install
            npm install -g pm2  # install pm2 if not already installed
            pm2 start npm --name "nextjs-app" -- run start
